name: Validate and Deploy Bicep to Azure
# this is a comment

on:
  push:
    branches:
      - main
    paths:
      - '**.bicep'  # Trigger only if Bicep files change

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: 'SERVICE_PRINCIPAL'
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Bicep
        run: |
          az deployment group validate \
            --resource-group sentinel-lab-iac-rg \
            --template-file main.bicep \
            --parameters workspaceName=sentinel-lab-iac-workspace param2=value2  # Add your parameters here if needed

      - name: Deploy Bicep
        run: |
          az deployment group create \
            --resource-group sentinel-lab-iac-rg \
            --template-file main.bicep \
            --parameters workspaceName=sentinel-lab-iac-workspace param2=value2  # Add your parameters here if needed
